### ISSUE TITLE
goroutine stack exceeds 1000000000-byte limit obtained on scan operation

### ISSUE THREAD

**Issue by timeforarchi** [cerberauth/vulnapi#225] opened 2024-11-29 08:52 UTC
Hi, 

just trying to use vulnapi scan on an api we developed (spring boot, kotlin, openapi V3 + swagger) and get a stack trace (attached)
Do I have to define GC/Memory elements on execution ?
[vulnapi-stack.txt](https://github.com/user-attachments/files/17956687/vulnapi-stack.txt)

It works perfectly with smaller microservice !

**Comment by emmanuelgautier** [comment] 2024-12-01 22:48
Hi @timeforarchi,

Thank you for reporting this and sorry for the issue you had with your OpenAPI file.

After reading your stack trace, your OpenAPI file may contain a parameter that references itself. This issue has been fixed in [PR #229](https://github.com/cerberauth/vulnapi/pull/229).

Without your OpenAPI file, I can't be completely certain this was the root cause of your error. Would you be able test it again with the new release v0.8.4?

**Closed** 2024-12-02 11:57 UTC
Labels: bug
